[package]
name = "base_token"
version = "0.1.0"
authors = ["Mason Fischer <mason@kissr.co>"]

[build-dependencies]
cask = "0.*"

[lib]
crate_type = ["cdylib"]

[dev-dependencies]
ellipticoin-test-framework = "0.1.0"

[dependencies]
ellipticoin = "0.1.0"
wee_alloc = { git = 'https://github.com/fitzgen/wee_alloc' }
wasm-rpc = "0.1.1"
cbor-no-std = "0.1.0"
