[package]
name = "base_token"
version = "0.1.0"
authors = ["Mason Fischer <mason@kissr.co>"]

[build-dependencies]
protoc-rust = "1.4"

[lib]
crate_type = ["cdylib"]

[dependencies]
protobuf = "1.*"
cask = "0.*"
