[workspace]
members = [
  "base_api",
  "user_contracts",
  "human_readable_name_registry",
  "base_token",
  "leader_election"
]

[profile.release]
opt-level = "z"
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
